### ISSUE TITLE
Where to put third-party apps expansion code?

### ISSUE THREAD

**Issue by ghost** [twoscoops/two-scoops-of-django-1.11#105]
## Location within the Book

* Chapter or Appendix: Chapter3 | How to Lay Out Django Projects
* Section: 3.2 Our Preferred Project Layout
* Subsection: None

## Description 

Suppose I use some excellent third-party apps but they couldn't cover all needs of my project in some point. Thus, I write some expansion code, such as more views, templatetags, even models.

However, I can not create an app that he name is same as the related third-party app if they both be added in `INSTALLED_APP` setting. But there are models and templatetags in expansion app, we have to do this.

My question is where to put such expansion app code? For now, I just create an app that the name is different from related third-party app. But I don't think is a good way. Further more, it seems  **core** app also isn't an suitable place.

How do you do that? Thanks for you advice!

**Comment by natecox** [comment]
I'm not sure I'm following the issue correctly. It _sounds_ like you want to extend or modify the functionality of a third party library, which is essentially [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch) and can lead to some pretty significant upgrade issues later on. _If_ this is the case, I would highly suggest that instead of making changes in-app, you instead [fork](https://help.github.com/articles/fork-a-repo/) the repo and create a downstream version for your intended use. If others can benefit from the changes that you're making you can then either release the fork as a viable alternative, or [create a pull request](https://help.github.com/articles/creating-a-pull-request/) to get your changes added to the original repo.

An example with a library and what you're doing to extend it would help.

**Comment by ghost** [comment]
Sorry, english is not my native language, so some expressions maybe ambiguous.

Let me show a simple example. Suppose I using a third-party app called **notification** in my project. But this app lacks some features which my project needs. Thus, I wrote some code to implement such features. For example, override some views, url paterns, add some templatetags. However, these features are related to **notification** but a little specific to my project.

What I want is just to put the code to an local app called **notification**, but this would conflict with original third-party app **notification** because they shared the same name.

**Comment by pydanny** [comment]
Don't create a new app with the same name or overwrite the original code (what @natecox warned you not to do). Instead, create a *new app with a different name*, perhaps `notification_extensions`. Then *extend* the existing code into new views and other things, piggybacking off the work of the original application. 

Do this because:

1. That way you aren't forking so you get the benefit of updates to the original work.
2. That way you aren't monkeypatching so you don't discover the hard way why the original code does things a certain way.
