### ISSUE TITLE
Django Channels

### ISSUE THREAD

**Issue by raiderrobert** [twoscoops/two-scoops-of-django-1.11#15]
I realize that channels isn't supposed to make it into Core for a little while yet. But I really think that channels will become a distinguishing feature for Django in the coming years, so a special blurb about it somewhere might be appropriate.

**Comment by natecox** [comment]
I've been mulling over this since I saw it posted as I wasn't really sure how I felt about the topic, but after considering the issue I actually agree with adding some blurb about channels into the book, but for a contrary reason: I don't view channels as a distinguishing feature for Django at all. In fact, every alternative framework that I've worked in recently has supported them, and largely out-of-the-box. They're becoming something of a standard feature, and I imagine that means we're going to start seeing more questions about them in the near future. May as well at least touch on the subject.

However, as I generally see Two Scoops as a reference for best practices, I'd be wary of diving too deeply. The subject matter is pretty new overall, and I don't think the community has really had time to digest it properly; i.e., I don't think we've had time to figure out what a best practice for web-sockets really is. Maybe it'd be best to just mention what they are, give a cursory overview of their role in Django, and then pass it on to the project docs themselves.

**Comment by pydanny** [comment]
@natecox, funny you should bring this up. We were just reviewing this and here's what we've learned that would fit in the context of the book:

* Be wary of using Channels to write spaghetti code
* Channel's generic consumers is a great tool for avoiding spaghetti code
* If you use Channels for asynchronous tasks, you **absolutely, positively** lose tasks in the queue. The package even warns of this.
* For connecting to browsers, use a JS library that can pick up dropped websocket connections.

And that's about it (unless we write a tutorial, which we try to avoid doing within TSD). That does not a chapter make. That's a few sections in other chapters.

We've added most of this advice to various parts of the book. That's probably where we are going to leave things.

**Comment by natecox** [comment]
@pydanny Sounds good to me.

**Comment by pydanny** [comment]
In the next update we'll have an appendix of general advice. @natecox, you want to take a look at it before we send it out?

**Comment by natecox** [comment]
Sure thing

**Comment by pydanny** [comment]
Okay, just sent you the email.

**Comment by raiderrobert** [comment]
Huzzah!
