### ISSUE TITLE
Migrations and Version Control

### ISSUE THREAD

**Issue by ohelal** [twoscoops/two-scoops-of-django-1.11#42]
## Location within the Book

* Chapter: 6
* Section: 6.2
* Subsection: 6.2.3 (*new?)

## Migrations and Version Control not mentioned in the book

Great work all round! Thank you.
I didn't see a mention on your position or the recommendation for version control vis-a-vis the migration files. 

- Do we ignore them? 

- Must we keep track of them? 

- Are there pros and cons or pitfalls?

Your feedback on this would be great and I would think more novices like myself might benefit from a mention of your position on the matter in the chapter that you discuss it. 
Thanks for taking the time out to read this and I wish you the best in your projects and plans.

**Comment by natecox** [comment]
Database migrations are designed to ensure that every developer working on your project always has a path to the most current version of the schema. They should absolutely be committed to your repository. 

Also, once they are committed to the repo they should _never be modified_ because this can cause some extremely difficult to debug development issues. It _might_ be acceptable to squash your migrations every once in a while, so long as you are in direct communication with every other developer and can ensure that everyone is up to date before the squash.

**Comment by pydanny** [comment]
To back up @natecox, here are the community recommendations (which we may find a place for in the books):

1. Putting your migrations in VCS is an absolute necessity
2. Don't modify existing migrations unless, as @natecox said, you are squashing them.
3. The pitfall of not putting migrations into VCS is that you are missing a critical component of your system design. It's like not including a base settings file in VCS: You might be able to develop, but should you switch machines or bring someone else into the project, then everything will just break.

**Comment by pydanny** [comment]
Added a tipbox and some other things instructing that migrations must always be in version control.

@ohelal, if you provide your full name I'll add you to the acknowledgement section of the book. 😄 

🍨 🚢

**Comment by ohelal** [comment]
Oh wow, that's wonderful.
Omar Helal is the name.
