### ISSUE TITLE
Change focus to Python 3.6+?

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#5]
On the fence.

Currently all code examples work with Python 2.7 and 3.x. If during the time that 1.11 is actively maintained by core, Python 2.7 is dropped, then perhaps focus should be changed to Python 3.

This would involve:

* Changing all code examples to follow Python 3 patterns exclusively
* Change the Python 3 chapter to be a regression chapter for Python 2.7 users.

**Comment by natecox** [comment]
I support this. At some point the python community is simply going to need to let go of 2.7, and having a source of authority adopt a 3+ only stance would go a long ways.

I think the only thing I have anymore that requires 2.7 is Fabric, and I know there's a port of it to 3+ already.

**Comment by oliwarner** [comment]
Just be careful what version of v3 you pick. There are some pretty big changes along the way. 3.6's literal strings are significantly different than older methods. I'd be hesitant to seize on those brand new features (which I'm sure we'll all _eventually_ be using) when **so** many users are pegged on 2.7  and 3.5.

Who's pegged? Linux users. We get maintained Python binaries from our distributions. Unless you're on a rolling release, that usually means that the major version never changes. For instance Ubuntu 16.04 will be on Python 3.5 for its entire lifespan. It's a LTS release so it's popular for developers and deployments and it'll be the main version of Ubuntu in deployments until after its successor releases in 2018.

So by all means, the major 3.x upgrades are great but be careful about what you're actually using from the new stuff. Some people won't be able to follow `async` directives.

**Comment by natecox** [comment]
I'm not sure that I find this to be a valid barrier to entry. I'm not aware of any system where it is not possible to install the latest python, and given the comprehensiveness of Two Scoops a basic instruction on doing so wouldn't be unexpected. E.g., for Ubuntu there's a PPA that provides basically every version of python so that you can install from `apt-get`. See http://askubuntu.com/questions/682869/how-do-i-install-newer-python-versions-using-apt-get

If you're working from inside a virtualenv, you don't need to worry about messing with the system python either. You can install whatever you want in parallel and just have the virutalenv use it as the default version.

**Comment by oliwarner** [comment]
I disagree. 

Every Django-on-Linux installation method I've seen to date uses the system Python. Even if you use a virtualenv (as you should) examples use system Python. I don't disagree you *can* do all sorts of things, but most developers don't.

Telling people to use PPAs for a foundation item like Python means you gain a huge chunk of extremely volatile and distribution-specific detail in the book. Indeed the guy who runs the popular Python PPA for Ubuntu displays how volatile PPAs are:

> Unfortunately, I don't have the time any more to keep up the previous update schedule. The exact future of this repository is undecided for now.

Not great for a book in print. Ubuntu 16.04 (and its v3.5 Python) will be around for years.

There could be a huge section on building Python for yourself. Huge because platforms vary and building Python isn't always non-trivial. And updates.

You're arguing that people should do something that almost no (citation needed) Django developers currently do, just so we can use the fancy new string formatting in examples? Come on. Save it for 2018 when people are _naturally_ using that version of Python.

**Comment by natecox** [comment]
> Come on. Save it for 2018 when people are naturally using that version of Python.

This is kind of my issue to start with. Right now we're still using python 2.7 as the industry standard, 8 years after python 3 was released (in December of 2008). Waiting for a normalization to occur before we push developers to adopt simply isn't going to work and I don't think we should be using it as a basis for a developer's guidebook to best practices.

I'm also wary of using a _bandwagon_ argument ("everyone else is using system python") as a basis for decision making. 

When it comes down to it, 3.5 is still better than 2.7, but I'd hate to end the discussion regarding 3.6+ simply because 3.5 is already installed on one group of user's systems.

**Comment by pydanny** [comment]
Thanks for the comments and thoughts from both sides.

I think this is enough of an issue that we'll specify to use Python 3+, but focus not on things like the new F strings and other recent developments. That way the book will be usable during the entire 2.5+ year Long Term Support (LTS) lifecycle of Django 1.11. 

For reference, we personally prefer to NOT use the system Python unless we have no choice. For example, our Elastic Beanstalk pet project keeps us on Python 3.4 even though we would prefer to jump to Python 3.6 as soon as it's released. But our docker-based projects will make the jump immediately to 3.6 because we have more control.

**Comment by pydanny** [comment]
The relevant appendix has been revised and usage of `django.utils.encoding.python_unicode_compatible` has been reduced across the book. Note: We instruct Python 2.7 users to use `django.utils.encoding.python_unicode_compatible` to see model representations.

**Comment by pydanny** [comment]
The introduction now includes the following text:

> While the book is tested on Python 3.6, we avoided the use of f-string literals. While we enjoy using f-strings, we wanted to ensure that our code examples worked on earlier versions of Python.
