### ISSUE TITLE
Consider showing URLs for links

### ISSUE THREAD

**Issue by alanwsmith** [twoscoops/two-scoops-of-django-1.11#53]
## Location within the Book

* Chapter: 2
* Section: 2.2
* Subsection: 2.2.1

## Overview

Please consider showing full URLs for links in the PDF version of the book. 

Doing so will help readers who:

- Imported the PDF into an app where links don't function properly.
- Printed out the PDF (e.g. because it's easier for them to read that way or they like hand writing notes)

While I'm using a specific example from section 2.2.1 here, the same feature would be useful for any link that's not itself a URL.

## Description 

Section 2.2.1 begins with: 

_We also highly recommend `virtualenvwrapper` for Mac OS X and Linux or `virtualenvwrapper-win` for Windows. The project was started by Doug Hellman._

When I import the PDF into the Kindle app (version 5.10 which is the latest as of today) on my iPad, both `virtualenvwrapper` and `virtualenvwrapper-win` show up as blue text that look like links but tapping on them doesn't work.

(The links do work properly when reading the PDF in the Preview app on macOS 10.12.4. So, the issue appears to be some interaction with the Kindle app.)

Searching for the words gets me to the right place. While I expect that will generally be the case, it creates a little unease. Wondering if I'm really looking at the right thing. 

It's relatively minor, but I'd love to have the actual URLs visible somewhere on the page so I could type them myself. Or, more likely, verify my search took me to the intended location.

**Comment by pydanny** [comment]
The problem is that Kindle software is **terrible** when it comes to rendering PDFs. The usual answer its shortcomings is to provide a dedicated `.mobi` or `.kpf` file for rendering of books on kindles and have proper PDF readers for PDF reading. At this point, we're probably not having a `.mobi` file, but we're looking at `.kpf` as that's trivial for us to do. The downside with `.kpf` is that it won't work with e-ink readers. 

As for correcting the links in the existing PDF, we can't economically do it. Doing so would cause havoc with formatting throughout the book that would take a full forty hours to fix. We're leery about spending so much time on links for one software package (kindle) that has known PDF issues.

Therefore, going forward, until we have an official kindle-friendly version of Two Scoops of Django, we recommend using Preview or a dedicated iOS PDF reader.
