### ISSUE TITLE
Add table mapping DRF behavior to REST Behavior

### ISSUE THREAD

**Issue by pydanny** [twoscoops/two-scoops-of-django-1.11#6]
DRF very precisely implements the REST API. For example, DRF treats PATCH as a partial update, but a some third-party REST implementations use POST but only executes changes on fields that are specified.

Two possible ways to handle this:

* Change "Rough SQL equivalent" in Table 16.1 HTTP Methods to list "PARTIAL UPDATE" for PATCH
* Create new table that specifies exact behavior (a'la DRF)

**Comment by natecox** [comment]
REST is one of my personal pet peeves because it's something that I end up using quite frequently and I see many implementations that ignore the "spirit" of the nomenclature. E.G., `POST` is for creating new entities, `PUT` is for replacing entities, `PATCH` is for partial updates, etc. This frustrates me greatly because much of the point of REST was implementing protocol nomenclature to simplify and clarify the intent of a request. 

Because of the above, I think I'd be careful in equating the protocol implementation with DRF itself; and would present them as the "technically correct" definitions in a single source. With that said, it's _probably_ best done in the REST section as a "detailed explanation", with a reference to it in the SQL equivalence table as "further information".

**Comment by pydanny** [comment]
Closing this as I think it's as good as it's going to get.
